#!/usr/bin/env python3

import argparse
import os
import sys
import requests

API_BASE = "http://10.0.1.62:8010/v1"
HOSTS_TAG = "__d-web-tag__"

def get_host(r_id):
    url = "%s/hosts" % API_BASE
    d = {
        "rv_id": r_id
        }
    rsp = requests.get(url, data=d)
    host = rsp.json().get("host")
    print("host: ", host)
    return host


def add_to_hosts(domain, host, r_id):
    uid = os.getuid()
    if uid != 0:
        print("E: must be run as root!")
        return False

    line = "%s %s # %s For cl %s, created by deepin-website-test-tool " %(host, domain, HOSTS_TAG, r_id)

    content = ""
    with open("/etc/hosts", "r") as fp:
        content = fp.read()

    # handle
    content = filter_repeat_domain(content, domain)
    content += "\n%s" % line

    with open("/etc/hosts", "w") as fp:
        fp.write(content)

    print("added hosts line:")
    print(" %s %s" %(host, domain))

    return True


def filter_repeat_domain(content, domain):
    lines = content.split("\n")
    filter_lines = []
    for line in lines:
        if HOSTS_TAG in line and domain in line:
            continue
        filter_lines.append(line)

    return "\n".join(filter_lines)


def del_from_hosts(domain):
    uid = os.getuid()
    if uid != 0:
        print("E: must be run as root!")
        return False

    del_lines = ""
    lines = ""
    with open("/etc/hosts", "r") as fp:
        while True:
            l = fp.readline()
            if HOSTS_TAG in l and domain in l:
                del_lines += l
                continue
            lines += l
            if len(l) == 0:
                break

    with open("/etc/hosts", "w") as fp:
        fp.write(lines)

    print("deleted hosts line(s):")
    print(del_lines)
    return True


def clear_all_hosts():
    del_lines = ""
    lines = ""
    with open("/etc/hosts", "r") as fp:
        while True:
            l = fp.readline()
            if HOSTS_TAG in l:
                del_lines += l
                continue
            lines += l
            if len(l) == 0:
                break

    with open("/etc/hosts", "w") as fp:
        fp.write(lines)

    print("cleared hosts line(s):")
    print(del_lines)
    return True


if __name__ == "__main__":

    parser = argparse.ArgumentParser()
    parser.add_argument("--site", help="website domain, eg: www.deepin.com", default="www.deepin.com")
    parser.add_argument("--num", help="change number of the commit")
    parser.add_argument("--action", choices=["add", "del", "clear"],
            default="add", help="add/del/clear hosts item added by this tool")
    args = parser.parse_args()

    site = args.site
    r_id = args.num
    action = args.action

    project = "sites/" + site

    if action == "add":
        if not site:
            print("--site options is required")
            quit(1)

        if not r_id:
            print("--id options is required")
            quit(1)

        host = get_host(r_id)
        if host:
            add_to_hosts(site, host, r_id)
        else:
            print("host not found in server")

    elif action == "del":
        if not site:
            print("--site options is required")
            quit(1)

        del_from_hosts(site)

    elif action == "clear":
        clear_all_hosts()

    else:
        print("Nothing has been done.")



